# Generated by Django 3.1.7 on 2021-03-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20210322_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='media/user_photo/'),
        ),
    ]
