# Generated by Django 3.1.7 on 2021-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_auto_20210326_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bio',
            field=models.TextField(default="I'm Empty", max_length=1500),
        ),
        migrations.AddField(
            model_name='blog',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update timestamp'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_post',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1500),
        ),
    ]
